name: Generate Snake

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Generate Snake (light + fire)
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: KAYABINGHI
          outputs: |
            dist/github-contribution-grid-snake-light.svg?palette=github-light&color_snake=#FF4500&color_dots=#FFB347,#FFD700,#FF6347,#FF8C00

      - name: Generate Snake (dark + fire)
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: KAYABINGHI
          outputs: dist/github-contribution-grid-snake-dark.svg?palette=github-dark&color_snake=#FF5733&color_dots=#FFD700,#FF4500,#FF6347,#FFA500

      - name: Push to output branch
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
